<div class="card-text">
    <?php if (count($results) > 0) : ?>
    <p>Similar authors to <?= $author->getName() ?></p>
        <ul>
            <?php foreach($results as $result): ?>
                <li>
                    <a href="?i=author:<?= $result[0] ?>"><?= $result[2] ?></a>&nbsp;<span class="text-muted">(<?= round(((float) $result[1]) * 100) ?> %)</span>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <em class="text-muted">There aren't any similar authors to <?= $author->getName() ?></em>
    <?php endif; ?>
</div>