<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>LOL (Large Online Library)</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="css/typeaheadjs.css" />
    <style>
        body { background: url('img/pattern.png') repeat; }
    </style>
</head>
<body>
<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-7 mx-auto text-center">
            <a href="/">
                <img src="/img/logo.png" width="180" />
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9 mx-auto">
            <form method="get" action="input/" class="d-flex flex-row">
                <input id="query-field" type="text" autocomplete="off" name="i" class="form-control mr-2" autofocus />
                <button type="submit" class="btn btn-primary align-self-end">Search</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-9 mt-4 mx-auto">
            <p>
                Example queries:
            </p>
            <ul>
                <li><a href="/input/?i=author:5">author:5</a> - Information about Alan H. Barr</li>
                <li><a href="/input/?i=author:4+author:736">author:4 author:736</a> - Collaborations between John C. Platt and John Shawe-Taylor </li>
                <li><a href="/input/?i=year:1998">year:1998</a> - Information about papers published in 1998</li>
                <li><a href="/input/?i=data+mining">data mining</a> - Papers about <code>data mining</code></li></li>
            </ul>
        </div>
    </div>
</div>
<script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="/js/typeahead.bundle.min.js"></script>
<script type="application/javascript">
$(document).ready(function() {
    var suggestions = new Bloodhound({
        datumTokenizer: function(d) {
            return Bloodhound.tokenizers.whitespace(d.name);
        },
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: 'api/suggest?q=%QUERY',
            wildcard: '%QUERY',
            rateLimitWait: 100
        }
    });

    suggestions.initialize();

    $('#query-field').typeahead(
        {
            highlight: true
        },
        {
            source: suggestions.ttAdapter()
        }
    );

});
</script>
</body>
</html>
