<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>LOL (Large Online Library)</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="css/typeaheadjs.css" />
</head>
<body>
<div class="container">
    <div class="row mt-4 mb-4">
        <div class="col-md-7 mx-auto">
            <h1 class="text-center">LOL</h1>
            <h6 class="text-center text-muted">Large Online Library</h6>
        </div>
    </div>
    <div class="row">
        <div class="col-md-7 mx-auto">
            <form method="get" action="input/" class="d-flex flex-row">
                <input type="text" autocomplete="off" name="i" class="form-control mr-2" autofocus />
                <button type="submit" class="btn btn-primary align-self-end">Search</button>
            </form>
        </div>
    </div>
</div>
<script
    src="https://code.jquery.com/jquery-3.2.1.min.js"
    integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
    crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="js/bootstrap3-typeahead.min.js"></script>
<script type="application/javascript">
  $("input[name=i]").typeahead({
     source: function(query, syncResults, asyncResults) {
       jQuery.get('api/suggest?q=' + query, function(data) {
         asyncResults(data);
       });},
     autoSelect: true
   });
</script>
</body>
</html>
