<?php
/** @var string $input */
/** @var \App\RenderableInterface[] $components */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>LOL (Large Online Library)</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="/css/typeaheadjs.css" />
    <style>
        body { background: url('/img/pattern.png') repeat; }
    </style>
</head>
<body>
    <div class="container">
        <div class="row mt-4 mb-4">
            <div class="col-md-12 mx-auto text-center">
                <a href="/">
                    <img src="/img/logo.png" width="180" />
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 mx-auto">
                <form method="get" action="" class="d-flex flex-row">
                    <input type="text" name="i" class="form-control mr-2" value="<?= $input ?>" />
                    <button type="submit" class="btn btn-primary align-self-end">Search</button>
                </form>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-12 mx-auto pb-5">
                <div class="card">
                    <h6 class="card-header">Input</h6>
                    <div class="card-body">
                        <p class="card-text"><?= $input ?></p>
                    </div>
                </div>
                <?php foreach ($components as $component) : ?>
                <div class="card mt-4">
                    <h6 class="card-header"><?= $component->getTitle() ?></h6>
                    <div class="card-body">
                        <?= $component->render() ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <script
        src="https://code.jquery.com/jquery-3.2.1.min.js"
        integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    <script type="application/javascript">
      $("input[name=i]").typeahead({
       source: function(query, syncResults, asyncResults) {
         jQuery.get('api/suggest?q=' + query, function(data) {
           asyncResults(data);
         });},
       autoSelect: true
     });
    </script>
    <script type="application/javascript">
      $('#documentModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget); // Button that triggered the modal
        var title = button.data('title'); // Extract info from data-* attributes
        var url = button.data('url');
        // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
        // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
        var modal = $(this);
        modal.find('.modal-title').text(title);
        modal.find('.modal-body iframe').attr('src', url);
        modal.find('a.external').attr('href', url);
      })
    </script>
</body>
</html>
