<?php
/** @var string $input */
/** @var \App\RenderableInterface[] $components */
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>LOL (Large Online Library)</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="row mt-4 mb-4">
            <div class="col-md-7 mx-auto">
                <h1 class="text-center">LOL</h1>
                <h6 class="text-center text-muted">Large Online Library</h6>
            </div>
        </div>
        <div class="row">
            <div class="col-md-7 mx-auto">
                <form method="get" action="" class="d-flex flex-row">
                    <input type="text" name="i" class="form-control mr-2" value="<?= $input ?>" />
                    <button type="submit" class="btn btn-primary align-self-end">Search</button>
                </form>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-md-7 mx-auto">
                <div class="card">
                    <h6 class="card-header">Input</h6>
                    <div class="card-body">
                        <p class="card-text"><?= $input ?></p>
                    </div>
                </div>
                <?php foreach ($components as $component) : ?>
                <div class="card mt-4">
                    <h6 class="card-header"><?= $component->getTitle() ?></h6>
                    <div class="card-body">
                        <?= $component->render() ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</body>
</html>
